apiVersion: auditor.appscode.com/v1alpha1
kind: AuditRegistration
resources:
#- group: apps
#  resources:
#  - deployments
#- group: ""
#  resources:
#  - pods
#  - namespaces
#  - secrets
- group: appcatalog.appscode.com
  resources:
  - appbindings
- group: catalog.kubedb.com
  resources:
  - etcdversions
  - mysqlversions
  - redisversions
  - mongodbversions
  - postgresversions
  - memcachedversions
  - elasticsearchversions
- group: kubedb.com
  resources:
  - etcds
  - mysqls
  - redises
  - mongodbs
  - snapshots
  - memcacheds
  - postgreses
  - elasticsearches
  - dormantdatabases
- group: monitoring.appscode.com
  resources:
  - incidents
  - podalerts
  - nodealerts
  - clusteralerts
  - searchlightplugins
- group: stash.appscode.com
  resources:
  - tasks
  - restics
  - functions
  - recoveries
  - repositories
  - backupbatches
  - backupsessions
  - restoresessions
  - backupblueprints
  - backupconfigurations
- group: voyager.appscode.com
  resources:
  - ingresses
  - certificates
